#pragma once

enum class EntityDamageCause {
	CAUSE_CONTACT = 0,
	CAUSE_ENTITY_ATTACK = 1,
	CAUSE_PROJECTILE = 2,
	CAUSE_SUFFOCATION = 3,
	CAUSE_FALL = 4,
	CAUSE_FIRE = 5,
	CAUSE_FIRE_TICK = 6,
	CAUSE_LAVA = 7,
	CAUSE_DROWNING = 8,
	CAUSE_BLOCK_EXPLOSION = 9,
	CAUSE_ENTITY_EXPLOSION = 10,
	CAUSE_VOID = 11,
	CAUSE_SUICIDE = 12,
	CAUSE_MAGIC = 13,
	CAUSE_CUSTOM = 14,
	CAUSE_STARVATION = 15,
	CAUSE_LIGHTNING = 16
};
